version: '3'

services:
  db:
    container_name: talkin_db
    image: postgres:latest
    restart: always
    env_file:
      - talkin.env
    ports:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  web:
    container_name: talkin_web
    build: ./backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers=4 
    env_file:
      - talkin.env  
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - staticfiles:/home/app/web/staticfiles/
      - mediafiles:/home/app/web/mediafiles/
  nginx:
    container_name: talkin_nginx
    image: nginx:mainline-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - staticfiles:/home/app/web/staticfiles/
      - mediafiles:/home/app/web/mediafiles/
    ports: 
      - "1343:80"
    depends_on:
      - web
volumes:
  postgres_data: